server:
  port: 0

spring:
  application:
    name: hotdeal-service
  # rabbit MQ 설정
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    loadbalancer:
      retry:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/hotdeal_service
    username: user
    password: password
    hikari:
      register-mbeans: true
    #   maximum-pool-size: 15       # 최대 커넥션 수 (기본값 10)
    #   minimum-idle: 10             # 최소 대기 커넥션 수
  data:
    redis:
      host: localhost
      port: 6379       
    
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

logging:
  level:
    org.springframework.cache: trace
    com.hong.hotdealservice: DEBUG
    com.hong.hotdealservice.client: DEBUG
    io.github.resilience4j.retry: INFO
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG

# resilience4j:
#   retry:
#     instances:
#       stockSaveRetry:
#         max-attempts: 3
#         wait-duration: 500ms
#         retry-exceptions:
#           - java.lang.Exception
#         ignore-exceptions:
#           - com.hong.common.exception.custom.HotDealProductException
