server:
  port: 0

spring:
  application:
    name: hotdeal-service
  # rabbit MQ 설정
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    loadbalancer:
      retry:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/hotdeal_service
    username: user
    password: password
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

logging:
  level:
    org.springframework.cache: trace
    com.hong.hotdealservice: DEBUG
    com.hong.hotdealservice.client: DEBUG
    io.github.resilience4j.retry: INFO

resilience4j:
  retry:
    instances:
      stockSaveRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.lang.Exception
        ignore-exceptions:
          - com.hong.common.exception.custom.HotDealProductException
