server:
  port: 0

spring:
  application:
    name: order-service
  # rabbit MQ 설정
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    loadbalancer:
      retry:
        enabled: false
         
  datasource:
    url: jdbc:mysql://localhost:3306/order_service?rewriteBatchedStatements=true
    username: user
    password: password
    hikari:
      register-mbeans: true
    #   maximum-pool-size: 20       # 최대 커넥션 수 (기본값 10)
    #   minimum-idle: 10             # 최소 대기 커넥션 수
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

logging:
  level:
    com.hong.orderservice: DEBUG
    com.hong.orderservice.client: DEBUG
    io.github.resilience4j.retry: INFO
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG