server:
  port: 0

spring:
  application:
    name: order-service
  # rabbit MQ 설정
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    loadbalancer:
      retry:
        enabled: false
         
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: user
    password: password
    hikari:
      maximum-pool-size: 16         
      minimum-idle: 10             
      idle-timeout: 600000       
      max-lifetime: 1800000      
      connection-timeout: 30000
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

logging:
  level:
    com.hong.orderservice: DEBUG
    com.hong.orderservice.client: DEBUG
    io.github.resilience4j.retry: INFO
